Strip down uniswap service and routes
CoinAlpha/gateway-api pull request #115
Opened 2021-07-27 10:28 UTC by vic-en

2021-07-27 10:33 UTC, vic-en reviewed
LGTM

2021-08-04 17:39 UTC, mifeng approved these changes

2021-08-06 18:59 UTC, mifeng requested changes
@vic-en 

There is still an issue where the client doesn't seem to recognize that a transaction has confirmed and doesn't place the 2nd leg of the trade. See this screenshot which shows the confirmed transaction on one side, and the client still waiting on the other side.

<img width="2555" alt="Screen Shot 2021-08-06 at 11 55 41 AM" src="https://user-images.githubusercontent.com/1795030/128559039-76acaab2-49bf-43a3-896a-60b12139e2be.png">

Is this an issue with the client? I'm using latest `development`

2021-08-06 19:10 UTC, mifeng commented
Actually, the issue I referenced above appears with the `master` and `development` branches of Gateway, so it appears unrelated to the changes made here. I will merge in this PR and ask QA to test AMM-ARB generally.

2021-08-06 19:10 UTC, merged