Feat/simplify uniswap v3
CoinAlpha/gateway-api pull request #119
Opened 2021-08-02 17:21 UTC by vic-en

This PR removes the pool caching logic in Uniswap v3.

2021-08-04 18:18 UTC, mifeng requested changes
In addition to the comments here, I couldn't get the `/price` endpoint to work. I passed in base: "DAI", quote: "WETH", amount: 100, side: "buy" but there was no response and no error after about 1 minute.

2021-08-04 18:18 UTC, mifeng commented on src/routes/uniswap_v3.ts
> +router.get('/order-pairs', async (req, res) => {
Changing the route would require changes to the client. The goal of this refactor should be to remove the pairs caching code while minimizing changes to the client needed.

2021-08-04 18:18 UTC, mifeng commented on src/routes/uniswap_v3.ts
> +        const price = parseFloat(trade.executionPrice.invert().toSignificant(8));
Applying both `parseFloat` and `toSignificant` seems a bit complex. Are both needed here?

2021-08-30 19:00 UTC, mifeng commented
@vic-en will add 1 more commit to this PR, after which we should merge to `development` and begin testing

2021-08-31 04:17 UTC, dennisocana commented
This is 1/3 pull requests we want to merge in the staging phase to be included in this upcoming Friday's release. As discussed during gateway standup, the current version of Uniswap v3 we have right now in production is not working + it's very complex to use.

The changes here are to simplify Uniswap v3 strategy even with outstanding issues, but a better version of what we currently have. Also adding QA as approver to sign-off before merging this in.

2021-08-31 13:50 UTC, RC-13 approved these changes
Approving PR in behalf of QA, issue seen during testing has been address by the last commit.

2021-08-31 14:22 UTC, mifeng approved these changes

2021-08-31 14:29 UTC, merged