Test/add test script for uniswap v3
CoinAlpha/gateway-api pull request #127
Opened 2021-08-09 12:43 UTC by vic-en

2021-08-14 05:32 UTC, PtrckM commented
**uniswap v2**
- getting undefined message
```
node -r esm tests/scripts/uniswap.v2.test.js
Trying to approve for invalid contract...
/eth/approve - Error: Request failed with status code 500
undefined
Trying to approve invalid token ABC...
/eth/approve - Error: Request failed with status code 500
undefined
Trying to approve invalid amount...
/eth/approve - Error: Request failed with status code 500
undefined
```

- logs `[ [Object], [Object], [Object], [Object] ]` 
```
Sell price: 1075.39130398
Executing buy trade on WETH-DAI with 0.01 amount...
Buy hash - 0x258a24d185f53967988a3b0e15e8159673e5be32901472b917172c8cc2534568
{
  network: 'kovan',
  timestamp: 1628916458198,
  latency: 2.396,
  txHash: '0x258a24d185f53967988a3b0e15e8159673e5be32901472b917172c8cc2534568',
  confirmed: true,
  receipt: {
    gasUsed: 98919,
    blockNumber: 26768258,
    confirmations: 11,
    status: 1,
    logs: [ [Object], [Object], [Object], [Object] ]
  }
}
Executing sell trade on WETH-DAI with 0.01 amount...
Buy hash - 0xa68ebc7e3200213787ca8e2218ee193833cace980c064c046075ede0122bcec2
{
  network: 'kovan',
  timestamp: 1628916527323,
  latency: 2.29,
  txHash: '0xa68ebc7e3200213787ca8e2218ee193833cace980c064c046075ede0122bcec2',
  confirmed: true,
  receipt: {
    gasUsed: 102431,
    blockNumber: 26768270,
    confirmations: 10,
    status: 1,
    logs: [ [Object], [Object], [Object], [Object] ]
  }
}
Testing for failure with extreme values of buy limitPrice...
/eth/uniswap/trade - Error: Request failed with status code 500
Testing for failure with extreme values of sell limitPrice...
/eth/uniswap/trade - Error: Request failed with status code 500
```

**uniswap v3**
- getting this warning during start
```
node -r esm tests/scripts/uniswap.v3.test.js
[ 'COIN2', 'COIN1' ]
Checking status of gateway server...
(node:15320) Warning: require() of ES modules is not supported.
require() of /home/ubuntu/add_test_script_for_uniswap_v3/tests/scripts/uniswap.v3.test.js is an ES module file as it is a .js file whose nearest parent package.json contains "type": "module" which defines all .js files in th
at package scope as ES modules.
Instead rename uniswap.v3.test.js to end in .cjs, change the requiring code to use import(), or remove "type": "module" from /home/ubuntu/add_test_script_for_uniswap_v3/package.json.
ok
```

- getting undefined message while testing on invalid..
```
Trying to approve for invalid contract...
/eth/approve - Error: Request failed with status code 500
undefined
Trying to approve invalid token ABC...
/eth/approve - Error: Request failed with status code 500
undefined
Trying to approve invalid amount...
/eth/approve - Error: Request failed with status code 500
undefined
```

- fail to add position
```
Starting Uniswap v3 on pair COIN2-COIN1...
{
  network: 'kovan',
  timestamp: 1628917555005,
  latency: 0,
  success: true,
  pairs: [ 'COIN1-COIN2' ],
  gasPrice: 38,
  gasLimit: 550688,
  gasCost: 0.020926144
}
Calling uniswap v3 gas-limit endpoint...
{ network: 'kovan', gasLimit: 550688, timestamp: 1628917555015 }
Checking mid price for COIN1-COIN2 on the MEDIUM fee tier...
Mid price: 0.00000000
Adding position on MEDIUM fee tier for COIN1-COIN2...
/eth/uniswap/v3/add-position - Error: Request failed with status code 500
(node:15320) UnhandledPromiseRejectionWarning: TypeError: Cannot convert undefined or null to object
    at Function.keys (<anonymous>)
    at Object.getOwnEnumerableProperties (/home/ubuntu/add_test_script_for_uniswap_v3/node_modules/chai/lib/chai/utils/getOwnEnumerableProperties.js:28:17)
    at Proxy.assertKeys (/home/ubuntu/add_test_script_for_uniswap_v3/node_modules/chai/lib/chai/core/assertions.js:2365:18)
    at Proxy.methodWrapper (/home/ubuntu/add_test_script_for_uniswap_v3/node_modules/chai/lib/chai/utils/addMethod.js:57:25)
    at Function.assert.hasAnyKeys (/home/ubuntu/add_test_script_for_uniswap_v3/node_modules/chai/lib/chai/interface/assert.js:1707:66)
    at unitTests (/home/ubuntu/add_test_script_for_uniswap_v3/tests/scripts/uniswap.v3.test.js:201:10)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async /home/ubuntu/add_test_script_for_uniswap_v3/tests/scripts/uniswap.v3.test.js:268:3
(node:15320) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .ca
tch(). (rejection id: 5)
(node:15320) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

tried DAI-USDC
```
Checking mid price for USDC-DAI on the MEDIUM fee tier...
/eth/uniswap/v3/price - Error: Request failed with status code 500
(node:15440) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'prices' of undefined
    at unitTests (/home/ubuntu/add_test_script_for_uniswap_v3/tests/scripts/uniswap.v3.test.js:188:38)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async /home/ubuntu/add_test_script_for_uniswap_v3/tests/scripts/uniswap.v3.test.js:268:3
(node:15440) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 5)
(node:15440) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

TxN: https://dashboard.tenderly.co/tx/kovan/0x73ac246caba83f24f54f7f795aa71118524c22a024ec958ad75f455590517a15

2021-08-19 18:18 UTC, martinkou requested changes

2021-08-19 18:18 UTC, martinkou commented on tests/README.md
> +PRIVATE_KEY: "********"
Don't put private key in a global config file - put it in a separate file, and check its permissions to make sure it's 0600, so it's inaccessible by other users.

2021-08-25 00:43 UTC, mifeng requested changes
I tested and the test script works.

Suggested changes:
- Separate the ethereum scripts into their own file. I see some rationale for testing approvals using the correct `spender` address, but I think this approach would result in a lot of duplicate code, so I think we should try to have a separate test script for the Ethereum function calls and ensure that the address constants are correct separately.
- Use `WETH` and `DAI` rather than `COIN1` and `COIN3` - I think it's important that we're interacting with testnet pools that other people are also testing againt, rather than our own custom tokens
- There may be more changes needed, but I think we should address the Uniswap V3 connector/strategy logic first.

2021-08-30 19:02 UTC, mifeng commented
The addition of the nonceManager here is intended to fix the approvals issue above for both Uniswap V2 and V3, after this PR and #119 are merged to `development`.

2021-08-31 04:43 UTC, dennisocana commented
This is 3/3 pull requests we want to merge in the staging phase to be included in this upcoming Friday's release. This includes the fix for https://github.com/CoinAlpha/gateway-api/issues/122. Adding QA as approver to sign-off before merging this in.

2021-08-31 04:59 UTC, PtrckM approved these changes
Tested and confirmed working. Approving in behalf of QA

2021-08-31 13:04 UTC, merged