(feat) Update postman collection & environment file for V2
CoinAlpha/gateway-api pull request #49
Opened 2021-04-01 01:00 UTC by sdgoh

Update Postman API for Gateway V2 as endpoints have changes in request parameters.

2021-04-03 06:08 UTC, PtrckM commented on test/postman/GatewayV2.postman_collection.json
> +											"value": "{{address}}",
should be `{{terraWalletAddress}}`

2021-04-03 06:12 UTC, PtrckM commented
should be `{{terraWalletAddress}}`
on https://github.com/CoinAlpha/gateway-api/pull/49/files#diff-46329a49b96b0fbec01a6ec9b2c88564b69f9d242bff5314a6d379d4bc152988R641

2021-04-14 16:34 UTC, vic-en requested changes

2021-04-14 16:34 UTC, vic-en commented on test/postman/GatewayV2.postman_collection.json
> +											"value": "{{address}}",
```suggestion
											"value": "{{terraWalletAddress}}",
```

2021-04-15 05:20 UTC, PtrckM approved these changes

2021-07-14 09:13 UTC, closed without merging