Refactor/architecture redesign es lint
CoinAlpha/gateway-api pull request #81
Opened 2021-06-03 11:20 UTC by james-hummingbot

2021-06-04 03:16 UTC, evseevnn requested changes

2021-06-04 03:23 UTC, evseevnn commented on src/services/uniswap.js
> +    const tx = await contract[result.methodName](...result.args, {
Yes, look like this method never use. I think we need write tests.

2021-06-04 08:47 UTC, evseevnn approved these changes
eslint and prettier configs looks good to me.

2021-06-07 03:55 UTC, dennisocana commented
For testing by @CoinAlpha/qa-team

2021-06-07 08:16 UTC, RC-13 commented
@james-hummingbot We can't seem to interact with any of the endpoints, currently blocked and getting connection refused, same behavior when checking from Hummingbot client. Are we missing something here? Cross-checked on the development branch and was able to interact with the endpoints using postman and Hummingbot client.
![image](https://user-images.githubusercontent.com/57189990/120982435-4b348400-c7ab-11eb-82fb-c150bc9cc079.png)

2021-06-07 08:31 UTC, rxlxrxsx commented
Running gateway without errors however the connection seems to be not established in the client

<img width="819" alt="Screen Shot 2021-06-07 at 2 33 43 PM" src="https://user-images.githubusercontent.com/64377055/120983105-f6ddd400-c7ab-11eb-9c2d-84c8aca064e8.png">

Tried to check in the client if I'll be able to run an amm_arb strategy or check the balance but failed

<img width="1423" alt="Screen Shot 2021-06-07 at 4 03 18 PM" src="https://user-images.githubusercontent.com/64377055/120983348-30aeda80-c7ac-11eb-9f2c-eff3237c1c87.png">

<img width="1424" alt="Screen Shot 2021-06-07 at 4 30 44 PM" src="https://user-images.githubusercontent.com/64377055/120985039-cc8d1600-c7ad-11eb-9045-c6b94570f058.png">

2021-06-08 03:05 UTC, RC-13 commented
Confirming the reported issue has been fixed.

2021-06-08 03:06 UTC, rxlxrxsx approved these changes
Tested and confirmed working by QA.

2021-06-08 03:16 UTC, merged