Refactor/add typescript
CoinAlpha/gateway-api pull request #88
Opened 2021-06-10 20:04 UTC by james-hummingbot

2021-06-13 09:42 UTC, evseevnn requested changes
Pls take a look on comments. If you have question you can ask me directly. I'll happy help you.

2021-06-13 09:42 UTC, evseevnn commented on package.json
> +    "start": "pm2 start babel-node --no-daemon -- dist/index.js",
Babel should be not use for production.

https://babeljs.io/docs/en/babel-node
> Not meant for production use
>
>You should not be using babel-node in production. It is unnecessarily heavy, with high memory usage due to the cache being stored in memory. You will also always experience a startup performance penalty as the entire app needs to be compiled on the fly.
>
>Check out the example Node.js server with Babel for an idea of how to use Babel in a production deployment.

You can use just regular `node`.

When you compile TypeScript code to js, in result you will get source code what you can use with regular `node`.

2021-06-13 09:42 UTC, evseevnn commented on package.json
> +    "start": "pm2 start babel-node --no-daemon -- dist/index.js",
Why you using pm2?
pm2 is great library, but I'm not sure that we really need to use it.

2021-06-13 09:42 UTC, evseevnn commented on src/index.ts
> +    console.log('listening on ' + bind);
We should stop using console.log but in current commit this is okay. I hope next time we will improve logging

2021-06-13 09:42 UTC, evseevnn commented on tsconfig.json
> +    "skipLibCheck": true /* Skip type checking of declaration files. */,
JSON does not support comments.

2021-06-13 09:46 UTC, evseevnn commented
> I see the problem, I was using `ts-node`, works if I switch to `babel-node`. Any suggestions to changes to package.json would be nice.

Actually for me all works fine with regular `node`. 

If you still need help ask me directly.

2021-06-14 02:14 UTC, RC-13 commented
@james-hummingbot I'm currently getting an error when running the `yarn run start` command, no issue when starting in debug mode (`yarn run debug`). Cross-checked the development branch and confirm that it only happens in this branch.
![yarn start error](https://user-images.githubusercontent.com/57189990/121831127-4c106d00-ccf9-11eb-92ee-038a96d09e8a.png)

2021-06-14 15:23 UTC, aarmoa approved these changes
I tested starting the gateway in my dev environment with the changes and it worked correctly.
I used the following sequence:
```
yarn
yarn build
yarn start dev
```

2021-06-14 20:47 UTC, evseevnn approved these changes

2021-06-14 23:11 UTC, RC-13 approved these changes
Tested and confirmed working by QA

2021-06-15 11:04 UTC, merged